[package]
name = "graphite"
version = "0.1.0"
authors = ["Keavon Chambers <graphite@keavon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
winit = "0.20"
wgpu = "0.5"
glsl-to-spirv = "0.1"
failure = "0.1.7"
cgmath = "0.17"
palette = "0.5"
futures = "0.3.4"
bytemuck = "1.2.0"
rctree = "0.3.3"
xmlparser = "0.13.1"
regex = "1.3.7"
css-color-parser = "0.1.2"
env_logger = { version = "0.7.1", optional = true }
euclid = "0.22.0"

[features]
debug = ["env_logger"]
