[package]
name = "graphite"
version = "0.1.0"
authors = ["Keavon Chambers <graphite@keavon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.8"
palette = "0.5.0"
futures = "0.3.5"
rctree = "0.3.3"
xmlparser = "0.13.2"
regex = "1.3.9"
css-color-parser = "0.1.2"
env_logger = { version = "0.7.1", optional = true }
bevy = "0.1.2"

[features]
debug = ["env_logger"]
